# This is a basic workflow to help you get started with Actions

name: Scrapy Cloud Job

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run-scrapy-cloud-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.8.5]
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.5
      - name: execute py script
        run: |
          python schedule_job.py
