# This is a basic workflow to help you get started with Actions

name: Scrapy Cloud Job Batch 7

on:
  schedule:
    - cron: "30 9,21 * * *"

jobs:
  run-scrapy-cloud-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.8]
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
      - name: execute py script
        run: |
          pipenv run python schedule_job.py Málaga Melilla Murcia Navarra Ourense Palencia Pontevedra
